"""create_phone_subscriptions

Revision ID: 0407ab247ce9
Revises: fde041cc62ad
Create Date: 2026-06-07 11:41:07.655986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0407ab247ce9'
down_revision: Union[str, Sequence[str], None] = 'fde041cc62ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telecom_center', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_type', sa.Enum('pstn', 'sip_phone', name='phonetypes'), nullable=True),
    sa.Column('user_sip_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pass_sip_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_sip_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_sub_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_subscriptions')
    # ### end Alembic commands ###
