"""create subscribers

Revision ID: 0d01f2798ea0
Revises: 81c85a93fc5b
Create Date: 2026-02-23 13:02:01.797388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0d01f2798ea0'
down_revision: Union[str, Sequence[str], None] = '81c85a93fc5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('father_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('national_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('certificate_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mobile', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('area', sa.Integer(), nullable=False),
    sa.Column('main_street', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('side_street', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alley', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('building_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('house_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subscriber_type', sa.Enum('real', 'legal', name='subscribertypes'), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    # ### end Alembic commands ###
