"""add is_active

Revision ID: 1770ae599cfb
Revises: a1e19c7367f1
Create Date: 2026-02-28 20:35:31.475601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1770ae599cfb'
down_revision: Union[str, Sequence[str], None] = 'a1e19c7367f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_ticket_id', sa.Integer(), nullable=True),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSE', name='ticket_status'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_ticket_id'], ['ticket_records.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['staffs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('subscribers', sa.Column('subscriber_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('subscribers', 'father_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscribers', 'national_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscribers', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('subscribers', 'certificate_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscribers', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscribers', 'province_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscribers', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscribers', 'area',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscribers', 'main_street',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscribers', 'side_street',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscribers', 'alley',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscribers', 'building_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscribers', 'house_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscribers', 'subscriber_type',
               existing_type=postgresql.ENUM('real', 'legal', name='subscribertypes'),
               nullable=True)
    op.add_column('tickets', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'is_active')
    op.alter_column('subscribers', 'subscriber_type',
               existing_type=postgresql.ENUM('real', 'legal', name='subscribertypes'),
               nullable=False)
    op.alter_column('subscribers', 'house_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscribers', 'building_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscribers', 'alley',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscribers', 'side_street',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscribers', 'main_street',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscribers', 'area',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscribers', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscribers', 'province_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscribers', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscribers', 'certificate_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscribers', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('subscribers', 'national_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscribers', 'father_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('subscribers', 'subscriber_code')
    op.drop_table('ticket_records')
    # ### end Alembic commands ###
