"""alter-corporation

Revision ID: 7f1dda2c48bd
Revises: a761176b1b62
Create Date: 2026-06-03 00:13:13.737626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f1dda2c48bd'
down_revision: Union[str, Sequence[str], None] = 'a761176b1b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('corporations_national_id_key'), 'corporations', type_='unique')
    op.drop_constraint(op.f('corporations_registration_number_key'), 'corporations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('corporations_registration_number_key'), 'corporations', ['registration_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('corporations_national_id_key'), 'corporations', ['national_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
