"""create_ticket_groups

Revision ID: d8ea160d383e
Revises: b09be80cbab8
Create Date: 2026-02-28 04:03:43.305525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd8ea160d383e'
down_revision: Union[str, Sequence[str], None] = 'b09be80cbab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_groups_title'), 'ticket_groups', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_groups_title'), table_name='ticket_groups')
    op.drop_table('ticket_groups')
    # ### end Alembic commands ###
