"""create_corporation

Revision ID: e6d6d3fa276f
Revises: 1770ae599cfb
Create Date: 2026-05-26 13:05:49.817265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e6d6d3fa276f'
down_revision: Union[str, Sequence[str], None] = '1770ae599cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('registration_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('national_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id'),
    sa.UniqueConstraint('registration_number'),
    sa.UniqueConstraint('subscriber_id')
    )
    op.add_column('subscribers', sa.Column('side_alley', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('subscribers', sa.Column('floor', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('subscribers', sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'unit')
    op.drop_column('subscribers', 'floor')
    op.drop_column('subscribers', 'side_alley')
    op.drop_table('corporations')
    # ### end Alembic commands ###
